/**
 * @File Name          : Example.cls
 * @Description        : This just created for the Example using the GIT Training module
 * @Author             : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Group              : 
 * @Last Modified By   : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Last Modified On   : 20/4/2020, 10:54:34 pm
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    20/4/2020          Sai Kiran              Initial Version
**/
public with sharing class Example {
    public Example() {
        System.debug( 'the Result of a file');
        System.debug( 'the Result of a  Second Debug Statement to GIT');

    }
}
