/**
 * @File Name          : Example2.cls
 * @Description        : Second class has created
 * @Author             : SaiKiran
 * @Group              : 
 * @Last Modified By   : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Last Modified On   : 21/4/2020, 12:05:20 am
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    21/4/2020   ChangeMeIn@UserSettingsUnder.SFDoc     Initial Version
**/
public with sharing class Example2 {
    public Example2() {
        System.debug('Second has created');
    }
}